import { CommonModule } from '@angular/common';
import { Component, DestroyRef, computed, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import {
  FormArray,
  FormBuilder,
  FormControl,
  FormGroup,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatButtonToggleModule } from '@angular/material/button-toggle';
import { MatCardModule } from '@angular/material/card';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSelectModule } from '@angular/material/select';
import { MatSnackBar } from '@angular/material/snack-bar';

import type {
  GenerationContributorOption,
  GenerationKnowledgeBaseOption,
  GenerationKnowledgeBaseOptions,
  GenerationMode,
  GenerationOptions,
  GenerationProjectFeatureOption,
  GenerationProjectHierarchyOption,
  GenerationProjectModuleOption,
  GenerationProjectPageOption,
  GenerationSelectedDatasetIds,
  GenerationSourceInput,
  GenerationSuiteContextInput,
  SourceKind,
  TestGenerationRunDetail,
  TestGenerationRunSummary,
} from '../../core/models';
import { GenerationMonitorService } from '../../core/generation-monitor.service';
import { AuthService } from '../../core/auth.service';
import { NotificationService } from '../../core/notification.service';
import { WorkbenchApiService } from '../../core/workbench-api.service';
import { EmptyStateComponent } from '../../shared/components/empty-state.component';
import { PageHeaderComponent } from '../../shared/components/page-header.component';

type KnowledgeFieldKey =
  | 'componentCatalogue'
  | 'featureType'
  | 'rulePack'
  | 'testTaxonomy'
  | 'scenarioTemplate'
  | 'severityMapping';

type DatasetSection = {
  key: KnowledgeFieldKey;
  label: string;
  description: string;
};

type SourceKindOption = {
  value: SourceKind;
  label: string;
  hint: string;
  glyph: string;
};

type ScreenSizeOption = {
  value: string;
  label: string;
  resolution: string;
};

type CoverageOptionKey =
  | 'includeSmoke'
  | 'includeFunctional'
  | 'includeNegative'
  | 'includeEdge'
  | 'includeUsability'
  | 'includeResponsiveness'
  | 'includeCompatibility';

type CoverageOption = {
  control: CoverageOptionKey;
  label: string;
  hint: string;
};

type ModeCard = {
  value: GenerationMode;
  title: string;
  summary: string;
  eyebrow: string;
};

type RunPreviewCase = {
  title: string;
  feature: string;
  scenario: string;
};

type ArchitectureInputMode = 'existing' | 'new';

@Component({
  selector: 'app-test-generation-page',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    RouterLink,
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatCheckboxModule,
    MatFormFieldModule,
    MatInputModule,
    MatProgressSpinnerModule,
    MatSelectModule,
    EmptyStateComponent,
    PageHeaderComponent,
  ],
  templateUrl: './test-generation-page.component.html',
  styleUrls: ['./test-generation-page.component.scss'],
})
export class TestGenerationPageComponent {
  private readonly fb = inject(FormBuilder);
  private readonly api = inject(WorkbenchApiService);
  private readonly notifications = inject(NotificationService);
  private readonly generationMonitor = inject(GenerationMonitorService);
  private readonly auth = inject(AuthService);
  private readonly destroyRef = inject(DestroyRef);
  private readonly snackBar = inject(MatSnackBar);
  private readonly router = inject(Router);

  private readonly formRevision = signal(0);
  private readonly titleManuallyEdited = signal(false);
  private lastAutoGeneratedTitle = 'Generated Test Suite Name';
  private autoTitleWriteInProgress = false;

  readonly loading = signal(true);
  readonly submitting = signal(false);
  readonly knowledgeBase = signal<GenerationKnowledgeBaseOptions | null>(null);
  readonly availableModules = signal<GenerationProjectModuleOption[]>([]);
  readonly availablePages = signal<GenerationProjectPageOption[]>([]);
  readonly availableFeatures = signal<GenerationProjectFeatureOption[]>([]);
  readonly activeRunId = signal<string | null>(null);
  readonly projectInputMode = signal<ArchitectureInputMode>('existing');
  readonly moduleInputMode = signal<ArchitectureInputMode>('existing');
  readonly pageInputMode = signal<ArchitectureInputMode>('existing');
  readonly featureInputMode = signal<ArchitectureInputMode>('existing');
  readonly contributorInputMode = signal<ArchitectureInputMode>('existing');
  readonly expandedSourceIndex = signal(-1);

  readonly modeCards: ModeCard[] = [
    {
      value: 'processAlpha',
      title: 'Source-Driven',
      summary: 'Infer feature coverage from supporting stories, mockups, notes, and uploaded evidence.',
      eyebrow: 'Launch from source material',
    },
    {
      value: 'processBeta',
      title: 'Knowledge Base-Driven',
      summary: 'Start from curated rule packs and feature sets, then sharpen coverage using supporting sources.',
      eyebrow: 'Launch from QA knowledge',
    },
  ];

  readonly sourceKindOptions: SourceKindOption[] = [
    { value: 'userStory', label: 'User Stories', hint: 'Story text, acceptance criteria, or refined tickets.', glyph: 'US' },
    { value: 'prd', label: 'PRD Notes', hint: 'Product requirements, technical specs, and design notes.', glyph: 'PRD' },
    { value: 'mockup', label: 'Mockups', hint: 'Figma or design URLs, annotated screenshots, HTML mockups, and visual evidence.', glyph: 'UI' },
    { value: 'image', label: 'Images', hint: 'Screenshots, wireframes, and chart snapshots.', glyph: 'IMG' },
    { value: 'file', label: 'Drop Files', hint: 'Word, PDF, Excel, CSV, or exported requirement documents.', glyph: 'FILE' },
    { value: 'link', label: 'Links', hint: 'Reference URL or external page relevant to the suite.', glyph: 'URL' },
    { value: 'note', label: 'KT Notes', hint: 'Pasted knowledge transfer notes or analyst context.', glyph: 'NOTE' },
    { value: 'video', label: 'Videos', hint: 'Demo recordings or walkthrough references.', glyph: 'VID' },
  ];

  readonly sourceTiles: SourceKindOption[] = [
    this.sourceKindOptions[0],
    this.sourceKindOptions[1],
    this.sourceKindOptions[2],
    this.sourceKindOptions[3],
    this.sourceKindOptions[6],
    this.sourceKindOptions[4],
  ];

  readonly datasetSections: DatasetSection[] = [
    {
      key: 'componentCatalogue',
      label: 'Components',
      description: 'Reusable UI elements and widget-level knowledge.',
    },
    {
      key: 'featureType',
      label: 'Feature Types',
      description: 'Product capability groupings and functional areas.',
    },
    {
      key: 'rulePack',
      label: 'Rule Packs',
      description: 'Behavioral rules, dashboard heuristics, and validations.',
    },
    {
      key: 'testTaxonomy',
      label: 'Test Taxonomy',
      description: 'Coverage taxonomies to steer breadth and categorization.',
    },
    {
      key: 'scenarioTemplate',
      label: 'Scenario Templates',
      description: 'Reusable scenario structures and testcase blueprints.',
    },
    {
      key: 'severityMapping',
      label: 'Severity Mapping',
      description: 'Severity heuristics for defect and risk classification.',
    },
  ];

  readonly browserOptions = ['Chrome', 'Firefox', 'Microsoft Edge', 'Safari'];
  readonly screenSizeOptions: ScreenSizeOption[] = [
    { value: 'desktop', label: 'Desktop', resolution: '1920 x 1080 px' },
    { value: 'laptop', label: 'Laptop', resolution: '1366 x 768 px' },
    { value: 'tablet', label: 'Tablet', resolution: '768 x 1024 px' },
    { value: 'mobile', label: 'Mobile', resolution: '390 x 844 px' },
    { value: '4K TV', label: '4K TV', resolution: '3840 x 2160 px' },
  ];
  readonly coverageOptions: CoverageOption[] = [
    { control: 'includeSmoke', label: 'Smoke', hint: 'Quick confidence on the main path.' },
    { control: 'includeFunctional', label: 'Functional', hint: 'Core behavior and user actions.' },
    { control: 'includeNegative', label: 'Negative', hint: 'Invalid and guarded user flows.' },
    { control: 'includeEdge', label: 'Edge', hint: 'Boundary states and special conditions.' },
    { control: 'includeUsability', label: 'Usability', hint: 'Clarity, labels, and interaction ease.' },
    { control: 'includeResponsiveness', label: 'Responsiveness', hint: 'Viewport and layout stability.' },
    { control: 'includeCompatibility', label: 'Compatibility', hint: 'Browser-specific consistency checks.' },
  ];
  readonly featureDraft = this.fb.nonNullable.control('');

  readonly form = this.fb.group({
    title: this.fb.nonNullable.control('Generated Test Suite Name', [Validators.required, Validators.maxLength(200)]),
    description: this.fb.nonNullable.control(''),
    mode: this.fb.nonNullable.control<GenerationMode>('processAlpha', Validators.required),
    contributorId: this.fb.nonNullable.control(''),
    contributorName: this.fb.nonNullable.control(''),
    projectId: this.fb.nonNullable.control(''),
    projectName: this.fb.nonNullable.control(''),
    moduleId: this.fb.nonNullable.control(''),
    moduleName: this.fb.nonNullable.control(''),
    pageId: this.fb.nonNullable.control(''),
    pageName: this.fb.nonNullable.control(''),
    featureId: this.fb.nonNullable.control(''),
    featureName: this.fb.nonNullable.control(''),
    sourceInputs: this.fb.array<FormGroup>([]),
    userFeatures: this.fb.array<FormGroup>([]),
    componentCatalogue: this.fb.nonNullable.control<string[]>([]),
    featureType: this.fb.nonNullable.control<string[]>([]),
    rulePack: this.fb.nonNullable.control<string[]>([]),
    testTaxonomy: this.fb.nonNullable.control<string[]>([]),
    scenarioTemplate: this.fb.nonNullable.control<string[]>([]),
    severityMapping: this.fb.nonNullable.control<string[]>([]),
    synonymAlias: this.fb.nonNullable.control<string[]>([]),
    includeSmoke: this.fb.nonNullable.control(true),
    includeFunctional: this.fb.nonNullable.control(true),
    includeNegative: this.fb.nonNullable.control(true),
    includeEdge: this.fb.nonNullable.control(true),
    includeUsability: this.fb.nonNullable.control(true),
    includeResponsiveness: this.fb.nonNullable.control(true),
    includeCompatibility: this.fb.nonNullable.control(true),
    targetBrowsers: this.fb.nonNullable.control<string[]>(['Chrome', 'Firefox', 'Microsoft Edge', 'Safari']),
    screenSizes: this.fb.nonNullable.control<string[]>(['desktop', 'laptop', 'tablet', 'mobile', '4K TV']),
  });

  readonly contributors = computed(() => {
    const currentUser = this.auth.currentUser();
    if (currentUser?.contributorId) {
      return [
        {
          id: currentUser.contributorId,
          name: currentUser.contributorName ?? currentUser.name,
          roleTitle: 'Signed-in user',
          accentColor: null,
        },
      ];
    }

    return this.knowledgeBase()?.contributors ?? [];
  });
  readonly currentUser = this.auth.currentUser;
  readonly projectHierarchy = computed(() => this.knowledgeBase()?.projectHierarchy ?? []);

  readonly selectedProject = computed(() => {
    this.formRevision();
    return this.findProject(this.form.controls.projectId.value);
  });
  readonly selectedModule = computed(() => {
    this.formRevision();
    return this.findModule(this.form.controls.moduleId.value);
  });
  readonly selectedPage = computed(() => {
    this.formRevision();
    return this.findPage(this.form.controls.pageId.value);
  });
  readonly selectedFeature = computed(() => {
    this.formRevision();
    return this.findFeature(this.form.controls.featureId.value);
  });
  readonly selectedContributor = computed(() => {
    this.formRevision();
    return this.findContributor(this.form.controls.contributorId.value);
  });

  readonly selectedSourceCount = computed(() => {
    this.formRevision();
    return this.getNormalizedSources().length;
  });

  readonly selectedKnowledgeItemCount = computed(() => {
    this.formRevision();
    return this.datasetSections.reduce((total, section) => total + this.getSelectionCount(section.key), 0);
  });

  readonly enabledCoverageCount = computed(() => {
    this.formRevision();
    return [
      this.form.controls.includeSmoke.value,
      this.form.controls.includeFunctional.value,
      this.form.controls.includeNegative.value,
      this.form.controls.includeEdge.value,
      this.form.controls.includeUsability.value,
      this.form.controls.includeResponsiveness.value,
      this.form.controls.includeCompatibility.value,
    ].filter(Boolean).length;
  });

  readonly selectedFeatureCount = computed(() => {
    this.formRevision();
    return this.getNormalizedUserFeatures().length;
  });
  readonly isFeatureScopeActive = computed(() => {
    this.formRevision();
    return Boolean(this.effectiveFeatureName().trim());
  });

  readonly currentTrackedRun = computed<TestGenerationRunSummary | TestGenerationRunDetail | null>(() => {
    const activeId = this.activeRunId() ?? this.generationMonitor.activeRuns()[0]?.id ?? null;
    if (!activeId) {
      return null;
    }

    return this.generationMonitor.getRunDetail(activeId) ?? this.generationMonitor.getRun(activeId);
  });

  readonly previewCases = computed(() => this.extractPreviewCases(this.currentTrackedRun()));
  readonly selectedBrowserSummary = computed(() => {
    this.formRevision();
    return this.buildBrowserSelectionSummary(this.form.controls.targetBrowsers.value);
  });
  readonly selectedScreenSizeSummary = computed(() => {
    this.formRevision();
    return this.buildScreenSizeSelectionSummary(this.form.controls.screenSizes.value);
  });

  constructor() {
    this.loadKnowledgeBase();

    this.form.valueChanges.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(() => {
      this.formRevision.update((value) => value + 1);
    });

    this.form.controls.projectId.valueChanges.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(() => {
      this.syncProjectHierarchy();
    });

    this.form.controls.moduleId.valueChanges.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(() => {
      this.syncPageOptions();
    });

    this.form.controls.projectName.valueChanges.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(() => {
      this.syncAutoGeneratedTitle();
    });

    this.form.controls.moduleName.valueChanges.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(() => {
      this.syncAutoGeneratedTitle();
    });

    this.form.controls.pageName.valueChanges.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(() => {
      this.syncAutoGeneratedTitle();
    });

    this.form.controls.pageId.valueChanges.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(() => {
      this.syncFeatureOptions();
    });

    this.form.controls.featureName.valueChanges.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(() => {
      this.syncFeatureScopeState();
      this.syncAutoGeneratedTitle();
    });

    this.form.controls.featureId.valueChanges.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(() => {
      this.syncFeatureScopeState();
      this.syncAutoGeneratedTitle();
    });

    this.form.controls.title.valueChanges.pipe(takeUntilDestroyed(this.destroyRef)).subscribe((value) => {
      if (this.autoTitleWriteInProgress) {
        return;
      }

      const normalized = String(value ?? '').trim();
      this.titleManuallyEdited.set(
        normalized.length > 0 &&
          normalized !== this.buildAutoGeneratedTitle() &&
          normalized !== this.lastAutoGeneratedTitle,
      );
    });
  }

  get sourceArray() {
    return this.form.controls.sourceInputs as FormArray<FormGroup>;
  }

  get featureArray() {
    return this.form.controls.userFeatures as FormArray<FormGroup>;
  }

  modeShortLabel(mode: GenerationMode) {
    return mode === 'processAlpha' ? 'Source' : mode === 'processBeta' ? 'KB' : 'Manual';
  }

  addSource(kind: SourceKind = 'note', options?: { expand?: boolean; scroll?: boolean }) {
    const nextIndex = this.sourceArray.length;
    this.sourceArray.push(this.createSourceGroup({ kind }));

    if (options?.expand ?? true) {
      this.expandedSourceIndex.set(nextIndex);
    }

    if (options?.scroll ?? true) {
      requestAnimationFrame(() => this.ensureSourceVisible(nextIndex));
    }

    return nextIndex;
  }

  addSourceFromTile(kind: SourceKind) {
    this.addSource(kind, { expand: true, scroll: true });
  }

  removeSource(index: number) {
    this.sourceArray.removeAt(index);

    if (!this.sourceArray.length) {
      this.expandedSourceIndex.set(-1);
      return;
    }

    const expandedIndex = this.expandedSourceIndex();
    if (expandedIndex === index) {
      this.expandedSourceIndex.set(Math.min(index, this.sourceArray.length - 1));
      return;
    }

    if (expandedIndex > index) {
      this.expandedSourceIndex.set(expandedIndex - 1);
    }
  }

  addFeature(value = this.featureDraft.value) {
    const trimmed = value.trim();
    if (!trimmed) {
      return;
    }

    const existing = new Set(this.getNormalizedUserFeatures().map((feature) => feature.toLowerCase()));
    if (existing.has(trimmed.toLowerCase())) {
      this.featureDraft.setValue('');
      return;
    }

    this.featureArray.push(this.createFeatureGroup(trimmed));
    this.featureDraft.setValue('');
  }

  removeFeature(index: number) {
    this.featureArray.removeAt(index);
  }

  optionsForSection(key: KnowledgeFieldKey): GenerationKnowledgeBaseOption[] {
    return this.knowledgeBase()?.[key] ?? [];
  }

  trackByValue(index: number, item: { id?: string; value?: string }) {
    return item.id ?? item.value ?? index;
  }

  getSelectionCount(key: KnowledgeFieldKey) {
    const value = this.form.controls[key].value;
    return Array.isArray(value) ? value.length : 0;
  }

  selectedTitlesForSection(key: KnowledgeFieldKey) {
    const selectedIds = new Set(this.form.controls[key].value ?? []);
    return this.optionsForSection(key)
      .filter((option) => selectedIds.has(option.id))
      .map((option) => option.title);
  }

  sourceKindMeta(kind: SourceKind) {
    return this.sourceKindOptions.find((option) => option.value === kind) ?? this.sourceKindOptions[6];
  }

  formatScreenSizeOptionLabel(value: string) {
    const option = this.screenSizeOptions.find((entry) => entry.value === value);
    return option ? `${option.label} (${option.resolution})` : value;
  }

  coverageOptionSelected(control: CoverageOptionKey) {
    return Boolean(this.form.controls[control].value);
  }

  isSourceExpanded(index: number) {
    return this.expandedSourceIndex() === index;
  }

  toggleSource(index: number) {
    const nextIndex = this.expandedSourceIndex() === index ? -1 : index;
    this.expandedSourceIndex.set(nextIndex);

    if (nextIndex >= 0) {
      requestAnimationFrame(() => this.ensureSourceVisible(nextIndex));
    }
  }

  selectAllSection(key: KnowledgeFieldKey) {
    this.form.controls[key].setValue(this.optionsForSection(key).map((option) => option.id));
  }

  clearSection(key: KnowledgeFieldKey) {
    this.form.controls[key].setValue([]);
  }

  areAllOptionsSelected(key: KnowledgeFieldKey) {
    const options = this.optionsForSection(key);
    if (!options.length) {
      return false;
    }

    return this.getSelectionCount(key) === options.length;
  }

  sourceCardTitle(index: number) {
    const source = this.sourceArray.at(index)?.getRawValue() as Record<string, string> | undefined;
    if (!source) {
      return `Source ${index + 1}`;
    }

    return this.sourceKindMeta((source['kind'] as SourceKind) ?? 'note').label;
  }

  sourceCardSubtitle(index: number) {
    const source = this.sourceArray.at(index)?.getRawValue() as Record<string, string> | undefined;
    if (!source) {
      return '';
    }

    const notes = source['notes']?.trim();
    if (notes) {
      return notes;
    }

    return this.sourceKindMeta((source['kind'] as SourceKind) ?? 'note').hint;
  }

  acceptedFileTypesForSource(kind: SourceKind | null | undefined) {
    switch (kind) {
      case 'mockup':
        return '.html,.htm,.xhtml,.fig,.pdf,.png,.jpg,.jpeg,.webp,.gif,.bmp,.svg,text/html,application/xhtml+xml,image/*';
      case 'image':
        return '.png,.jpg,.jpeg,.webp,.gif,.bmp,.svg,image/*';
      case 'video':
        return '.mp4,.mov,.avi,.webm,video/*';
      case 'file':
        return '.pdf,.doc,.docx,.xls,.xlsx,.csv,.txt,.md,.json,.yaml,.yml,.xml,.html,.htm,.xhtml,text/*,application/pdf,application/json,application/xml,application/xhtml+xml,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel';
      default:
        return '.txt,.md,.json,.yaml,.yml,.xml,.html,.htm,.xhtml,.pdf,.doc,.docx,.xls,.xlsx,.csv,.png,.jpg,.jpeg,.webp,.gif,.bmp,.svg,text/*,image/*,application/json,application/xml,application/xhtml+xml,application/pdf';
    }
  }

  getNormalizedUserFeatures() {
    const seen = new Set<string>();
    const values: string[] = [];

    for (const control of this.featureArray.controls) {
      const raw = String(control.get('value')?.value ?? '').trim();
      if (!raw) {
        continue;
      }

      const normalized = raw.toLowerCase();
      if (seen.has(normalized)) {
        continue;
      }

      seen.add(normalized);
      values.push(raw);
    }

    return values;
  }

  async onSourceFileSelected(index: number, event: Event) {
    const input = event.target as HTMLInputElement | null;
    const files = Array.from(input?.files ?? []);
    if (!files.length) {
      return;
    }

    const group = this.sourceArray.at(index);
    const sourceKind = (group.get('kind')?.value as SourceKind | undefined) ?? 'file';

    try {
      const preparedFiles = await Promise.all(files.map((file) => this.buildFileBackedSource(sourceKind, file)));
      const [primaryFile, ...additionalFiles] = preparedFiles;

      group.patchValue(primaryFile);

      additionalFiles.forEach((source, offset) => {
        this.sourceArray.insert(index + offset + 1, this.createSourceGroup(source));
      });

      this.expandedSourceIndex.set(index);
      requestAnimationFrame(() => this.ensureSourceVisible(index));
    } catch {
      this.notifications.error('Unable to read the selected file.');
    } finally {
      if (input) {
        input.value = '';
      }
    }
  }

  submit() {
    if (this.form.controls.title.invalid) {
      this.form.controls.title.markAsTouched();
      this.notifications.error('Enter a suite title before launching generation.');
      return;
    }

    const payload = {
      title: this.form.controls.title.value.trim(),
      description: this.form.controls.description.value.trim(),
      mode: this.form.controls.mode.value,
      sourceInputs: this.getNormalizedSources(),
      userFeatures: this.getNormalizedUserFeatures(),
      suiteContext: this.getSuiteContext(),
      selectedDatasetIds: this.getSelectedDatasetIds(),
      generationOptions: this.getGenerationOptions(),
    };

    this.submitting.set(true);

    this.api
      .createGenerationRun(payload)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: ({ run }) => {
          this.submitting.set(false);
          this.activeRunId.set(run.id);
          this.generationMonitor.trackRun(run);
          const ref = this.snackBar.open(`${payload.title} is now generating.`, 'View runs', {
            duration: 9000,
            panelClass: ['snackbar-success'],
          });

          ref.onAction().pipe(takeUntilDestroyed(this.destroyRef)).subscribe(() => {
            void this.router.navigate(['/test-generator/runs']);
          });
        },
        error: (error) => {
          this.submitting.set(false);
          const message =
            typeof error?.error?.message === 'string'
              ? error.error.message
              : 'Unable to launch test generation right now.';
          this.notifications.error(message);
        },
      });
  }

  suitePathLabel() {
    const parts = [
      this.effectiveProjectName(),
      this.effectiveModuleName(),
      this.effectivePageName(),
      this.effectiveFeatureName(),
    ].filter(Boolean);
    return parts.length ? parts.join(' / ') : '';
  }

  scopePillLabel() {
    return this.isFeatureScopeActive() ? 'Feature scope' : 'Page scope';
  }

  currentModeCard() {
    return this.modeCards.find((item) => item.value === this.form.controls.mode.value) ?? this.modeCards[0];
  }

  setMode(mode: GenerationMode) {
    this.form.controls.mode.setValue(mode);
  }

  setProjectInputMode(mode: ArchitectureInputMode) {
    if (mode === this.projectInputMode()) {
      return;
    }

    this.projectInputMode.set(mode);

    if (mode === 'new') {
      this.form.controls.projectId.setValue('');
      this.form.controls.moduleId.setValue('');
      this.form.controls.pageId.setValue('');
    } else {
      this.form.controls.projectName.setValue('');
    }

    this.syncProjectHierarchy();
    this.syncAutoGeneratedTitle();
  }

  setModuleInputMode(mode: ArchitectureInputMode) {
    if (mode === this.moduleInputMode()) {
      return;
    }

    this.moduleInputMode.set(mode);

    if (mode === 'new') {
      this.form.controls.moduleId.setValue('');
      this.form.controls.pageId.setValue('');
    } else {
      this.form.controls.moduleName.setValue('');
    }

    this.syncPageOptions();
    this.syncAutoGeneratedTitle();
  }

  setPageInputMode(mode: ArchitectureInputMode) {
    if (mode === this.pageInputMode()) {
      return;
    }

    this.pageInputMode.set(mode);

    if (mode === 'new') {
      this.form.controls.pageId.setValue('');
    } else {
      this.form.controls.pageName.setValue('');
    }

    this.syncFeatureOptions();
  }

  setFeatureInputMode(mode: ArchitectureInputMode) {
    if (mode === this.featureInputMode()) {
      return;
    }

    this.featureInputMode.set(mode);

    if (mode === 'new') {
      this.form.controls.featureId.setValue('');
    } else {
      this.form.controls.featureName.setValue('');
    }

    this.syncFeatureScopeState();
    this.syncAutoGeneratedTitle();
  }

  setContributorInputMode(mode: ArchitectureInputMode) {
    if (mode === this.contributorInputMode()) {
      return;
    }

    this.contributorInputMode.set(mode);

    if (mode === 'new') {
      this.form.controls.contributorId.setValue('');
    } else {
      this.form.controls.contributorName.setValue('');
    }
  }

  progressWidth(run: TestGenerationRunSummary | TestGenerationRunDetail | null) {
    if (!run?.progress) {
      return run?.status === 'completed' ? 100 : 14;
    }

    const total = run.progress.totalBatches || 0;
    if (!total) {
      return run.status === 'completed' ? 100 : 18;
    }

    return Math.max(12, Math.min(100, (run.progress.completedBatches / total) * 100));
  }

  formatRunPhase(run: TestGenerationRunSummary | TestGenerationRunDetail | null) {
    const phase = run?.progress?.phase;
    switch (phase) {
      case 'initial_generation':
        return 'Generating unit batches';
      case 'coverage_validation':
        return 'Validating coverage';
      case 'remediation':
        return 'Filling missing coverage';
      case 'finalizing':
        return 'Finalizing suite draft';
      case 'completed':
        return 'Ready for review';
      case 'failed':
        return 'Generation failed';
      case 'queued':
      default:
        return 'Queued for generation';
    }
  }

  hasPreviewCases(run: TestGenerationRunSummary | TestGenerationRunDetail | null) {
    return this.extractPreviewCases(run).length > 0;
  }

  stopTrackedRun() {
    const run = this.currentTrackedRun();
    if (!run || run.status !== 'pending') {
      return;
    }

    this.api
      .stopGenerationRun(run.id)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: ({ run: updatedRun }) => {
          this.generationMonitor.trackRun(updatedRun);
          this.notifications.success(`${updatedRun.title} was stopped.`);
        },
        error: (error) => {
          const message =
            typeof error?.error?.message === 'string'
              ? error.error.message
              : 'Unable to stop generation right now.';
          this.notifications.error(message);
        },
      });
  }

  openFirstPendingReview() {
    const run = this.currentTrackedRun();
    return run?.draftId ? ['/test-generator/review'] : null;
  }

  private createSourceGroup(source?: Partial<GenerationSourceInput>) {
    return this.fb.group({
      kind: this.fb.nonNullable.control<SourceKind>(source?.kind ?? 'note'),
      label: this.fb.nonNullable.control(source?.label ?? ''),
      filename: this.fb.nonNullable.control(source?.filename ?? ''),
      mimeType: this.fb.nonNullable.control(source?.mimeType ?? ''),
      contentText: this.fb.nonNullable.control(source?.contentText ?? ''),
      dataUrl: this.fb.nonNullable.control(source?.dataUrl ?? ''),
      url: this.fb.nonNullable.control(source?.url ?? ''),
      notes: this.fb.nonNullable.control(source?.notes ?? ''),
    });
  }

  private createFeatureGroup(value = '') {
    return this.fb.group({
      value: this.fb.nonNullable.control(value),
    });
  }

  private loadKnowledgeBase() {
    this.api
      .getGenerationKnowledgeBase()
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (result) => {
          this.knowledgeBase.set(result);
          this.loading.set(false);
          this.applyDefaultSelections(result);
          this.syncProjectHierarchy();
        },
        error: () => {
          this.loading.set(false);
          this.notifications.error('Unable to load generator setup data.');
        },
      });
  }

  private buildBrowserSelectionSummary(values: string[]) {
    if (!Array.isArray(values) || !values.length) {
      return 'Not selected';
    }

    return values.join(', ');
  }

  private buildScreenSizeSelectionSummary(values: string[]) {
    if (!Array.isArray(values) || !values.length) {
      return 'Not selected';
    }

    return values
      .map((value) => this.screenSizeOptions.find((option) => option.value === value)?.label ?? value)
      .join(', ');
  }

  private applyDefaultSelections(result: GenerationKnowledgeBaseOptions) {
    const currentUser = this.auth.currentUser();
    if (currentUser?.contributorId) {
      this.form.controls.contributorId.setValue(currentUser.contributorId);
      this.form.controls.contributorName.setValue(currentUser.contributorName ?? currentUser.name);
      this.contributorInputMode.set('existing');
    } else if (!this.form.controls.contributorId.value && result.contributors.length === 1) {
      this.form.controls.contributorId.setValue(result.contributors[0].id);
    }

    if (!this.form.controls.projectId.value && result.projectHierarchy.length === 1) {
      this.form.controls.projectId.setValue(result.projectHierarchy[0].id);
    }

    this.syncAutoGeneratedTitle(true);
  }

  private syncProjectHierarchy() {
    if (this.projectInputMode() === 'new') {
      this.availableModules.set([]);
      this.availablePages.set([]);
      this.availableFeatures.set([]);

      if (this.moduleInputMode() === 'existing') {
        this.form.controls.moduleId.setValue('');
      }

      if (this.pageInputMode() === 'existing') {
        this.form.controls.pageId.setValue('');
      }

      if (this.featureInputMode() === 'existing') {
        this.form.controls.featureId.setValue('');
      }

      this.syncAutoGeneratedTitle();
      return;
    }

    const project = this.findProject(this.form.controls.projectId.value);
    const modules = project?.modules ?? [];
    this.availableModules.set(modules);

    const moduleExists = modules.some((item) => item.id === this.form.controls.moduleId.value);
    if (!moduleExists) {
      this.form.controls.moduleId.setValue(modules.length === 1 ? modules[0].id : '');
    }

    this.syncPageOptions();
    this.syncAutoGeneratedTitle();
  }

  private syncPageOptions() {
    if (this.projectInputMode() === 'new' || this.moduleInputMode() === 'new') {
      this.availablePages.set([]);

      if (this.pageInputMode() === 'existing') {
        this.form.controls.pageId.setValue('');
      }

      this.syncFeatureOptions();
      return;
    }

    const module = this.findModule(this.form.controls.moduleId.value);
    const pages = module?.pages ?? [];
    this.availablePages.set(pages);

    const pageExists = pages.some((item) => item.id === this.form.controls.pageId.value);
    if (!pageExists) {
      this.form.controls.pageId.setValue(pages.length === 1 ? pages[0].id : '');
    }

    this.syncFeatureOptions();
  }

  private syncFeatureOptions() {
    if (
      this.projectInputMode() === 'new' ||
      this.moduleInputMode() === 'new' ||
      this.pageInputMode() === 'new'
    ) {
      this.availableFeatures.set([]);

      if (this.featureInputMode() === 'existing') {
        this.form.controls.featureId.setValue('');
      }

      this.syncFeatureScopeState();
      this.syncAutoGeneratedTitle();
      return;
    }

    const page = this.findPage(this.form.controls.pageId.value);
    const features = page?.features ?? [];
    this.availableFeatures.set(features);

    const featureExists = features.some((item) => item.id === this.form.controls.featureId.value);
    if (!featureExists) {
      this.form.controls.featureId.setValue('');
    }

    this.syncFeatureScopeState();
    this.syncAutoGeneratedTitle();
  }

  private effectiveProjectName() {
    if (this.projectInputMode() === 'new') {
      return this.form.controls.projectName.value.trim();
    }

    return this.resolveExistingProjectName();
  }

  private effectiveModuleName() {
    if (this.moduleInputMode() === 'new') {
      return this.form.controls.moduleName.value.trim();
    }

    return this.resolveExistingModuleName();
  }

  private effectivePageName() {
    if (this.pageInputMode() === 'new') {
      return this.form.controls.pageName.value.trim();
    }

    return this.resolveExistingPageName();
  }

  private effectiveFeatureName() {
    if (this.featureInputMode() === 'new') {
      return this.form.controls.featureName.value.trim();
    }

    return this.resolveExistingFeatureName();
  }

  private effectiveContributorName() {
    const currentUser = this.auth.currentUser();
    return (
      currentUser?.contributorName?.trim() ||
      currentUser?.name?.trim() ||
      this.form.controls.contributorName.value.trim() ||
      (this.selectedContributor()?.name ?? '').trim()
    );
  }

  private buildAutoGeneratedTitle() {
    const projectName = this.effectiveProjectName().trim();
    const moduleName = this.effectiveModuleName().trim();
    const pageName = this.effectivePageName().trim();
    const featureName = this.effectiveFeatureName().trim();

    if (projectName && moduleName && pageName && featureName) {
      return [projectName, moduleName, pageName, featureName].join('-');
    }

    if (projectName && moduleName && pageName) {
      return [projectName, moduleName, pageName].join('-');
    }

    return 'Generated Test Suite Name';
  }

  private syncAutoGeneratedTitle(force = false) {
    const currentTitle = this.form.controls.title.value.trim();
    const canOverwrite =
      force ||
      !this.titleManuallyEdited() ||
      !currentTitle ||
      currentTitle === 'Generated Test Suite Name' ||
      currentTitle === this.lastAutoGeneratedTitle;

    if (!canOverwrite) {
      return;
    }

    const nextTitle = this.buildAutoGeneratedTitle();
    this.lastAutoGeneratedTitle = nextTitle;
    if (currentTitle === nextTitle) {
      this.titleManuallyEdited.set(false);
      return;
    }

    this.autoTitleWriteInProgress = true;
    this.form.controls.title.setValue(nextTitle);
    this.autoTitleWriteInProgress = false;
    this.titleManuallyEdited.set(false);
  }

  private fallbackProjectName() {
    return 'Unassigned Client';
  }

  private fallbackModuleName() {
    return 'Unassigned Module';
  }

  private fallbackPageName() {
    return 'Unassigned Page';
  }

  private findProject(projectId: string) {
    return this.projectHierarchy().find((item) => item.id === projectId) ?? null;
  }

  private findModule(moduleId: string) {
    if (!moduleId) {
      return null;
    }

    for (const project of this.projectHierarchy()) {
      const module = project.modules.find((item) => item.id === moduleId);
      if (module) {
        return module;
      }
    }

    return null;
  }

  private findPage(pageId: string) {
    if (!pageId) {
      return null;
    }

    for (const project of this.projectHierarchy()) {
      for (const module of project.modules) {
        const page = module.pages.find((item) => item.id === pageId);
        if (page) {
          return page;
        }
      }
    }

    return null;
  }

  private findFeature(featureId: string) {
    if (!featureId) {
      return null;
    }

    for (const project of this.projectHierarchy()) {
      for (const module of project.modules) {
        for (const page of module.pages) {
          const feature = page.features.find((item) => item.id === featureId);
          if (feature) {
            return feature;
          }
        }
      }
    }

    return null;
  }

  private findContributor(contributorId: string) {
    return this.contributors().find((item) => item.id === contributorId) ?? null;
  }

  private getNormalizedSources(): GenerationSourceInput[] {
    return this.sourceArray.controls
      .map((control) => {
        const value = control.getRawValue() as Record<string, string>;
        const hasContent = [
          value['label'],
          value['filename'],
          value['mimeType'],
          value['contentText'],
          value['dataUrl'],
          value['url'],
          value['notes'],
        ].some((entry) => String(entry ?? '').trim().length > 0);

        if (!hasContent) {
          return null;
        }

        const derivedLabel = this.deriveSourceLabel(value);
        const normalized: GenerationSourceInput = {
          kind: (value['kind'] as SourceKind) || 'note',
          label: derivedLabel,
        };

        const filename = value['filename'].trim();
        const mimeType = value['mimeType'].trim();
        const contentText = value['contentText'].trim();
        const dataUrl = value['dataUrl'].trim();
        const url = value['url'].trim();
        const notes = value['notes'].trim();

        if (filename) {
          normalized.filename = filename;
        }

        if (mimeType) {
          normalized.mimeType = mimeType;
        }

        if (contentText) {
          normalized.contentText = contentText;
        }

        if (dataUrl) {
          normalized.dataUrl = dataUrl;
        }

        if (url) {
          normalized.url = url;
        }

        if (notes) {
          normalized.notes = notes;
        }

        return normalized;
      })
      .filter((item): item is GenerationSourceInput => item !== null);
  }

  private deriveSourceLabel(value: Record<string, string>) {
    const explicitLabel = value['label']?.trim();
    if (explicitLabel) {
      return explicitLabel;
    }

    const filename = value['filename']?.trim();
    if (filename) {
      return filename;
    }

    const contentText = value['contentText']?.trim();
    if (contentText) {
      return `${this.sourceKindMeta((value['kind'] as SourceKind) ?? 'note').label} excerpt`;
    }

    const notes = value['notes']?.trim();
    if (notes) {
      return `${this.sourceKindMeta((value['kind'] as SourceKind) ?? 'note').label} notes`;
    }

    return this.sourceKindMeta((value['kind'] as SourceKind) ?? 'note').label;
  }

  private resolveExistingProjectName() {
    const directProject = this.selectedProject()?.name?.trim();
    if (directProject) {
      return directProject;
    }

    const moduleId = this.form.controls.moduleId.value;
    if (moduleId) {
      for (const project of this.projectHierarchy()) {
        if (project.modules.some((module) => module.id === moduleId)) {
          return project.name.trim();
        }
      }
    }

    const pageId = this.form.controls.pageId.value;
    if (pageId) {
      for (const project of this.projectHierarchy()) {
        if (project.modules.some((module) => module.pages.some((page) => page.id === pageId))) {
          return project.name.trim();
        }
      }
    }

    return '';
  }

  private resolveExistingModuleName() {
    const directModule = this.selectedModule()?.name?.trim();
    if (directModule) {
      return directModule;
    }

    const pageId = this.form.controls.pageId.value;
    if (pageId) {
      for (const project of this.projectHierarchy()) {
        for (const module of project.modules) {
          if (module.pages.some((page) => page.id === pageId)) {
            return module.name.trim();
          }
        }
      }
    }

    return '';
  }

  private resolveExistingPageName() {
    return this.selectedPage()?.name?.trim() ?? '';
  }

  private resolveExistingFeatureName() {
    return this.selectedFeature()?.name?.trim() ?? '';
  }

  private syncFeatureScopeState() {
    if (!this.effectiveFeatureName().trim()) {
      return;
    }

    if (this.featureArray.length) {
      this.featureArray.clear();
    }

    if (this.featureDraft.value.trim()) {
      this.featureDraft.setValue('');
    }
  }

  private getSuiteContext(): GenerationSuiteContextInput {
    const projectId =
      this.projectInputMode() === 'existing' ? this.form.controls.projectId.value || undefined : undefined;
    const moduleId =
      this.moduleInputMode() === 'existing' ? this.form.controls.moduleId.value || undefined : undefined;
    const pageId = this.pageInputMode() === 'existing' ? this.form.controls.pageId.value || undefined : undefined;
    const featureId =
      this.featureInputMode() === 'existing' ? this.form.controls.featureId.value || undefined : undefined;

    const projectName = this.effectiveProjectName() || this.fallbackProjectName();
    const moduleName = this.effectiveModuleName() || this.fallbackModuleName();
    const pageName = this.effectivePageName() || this.fallbackPageName();
    const featureName = this.effectiveFeatureName() || undefined;
    const currentUser = this.auth.currentUser();
    const contributorId = currentUser?.contributorId?.trim() || this.form.controls.contributorId.value || undefined;

    return {
      contributorId,
      contributorName: this.effectiveContributorName() || undefined,
      projectId,
      projectName,
      moduleId,
      moduleName,
      pageId,
      pageName,
      featureId,
      featureName,
    };
  }

  private getSelectedDatasetIds(): GenerationSelectedDatasetIds {
    return {
      componentCatalogue: [...this.form.controls.componentCatalogue.value],
      featureType: [...this.form.controls.featureType.value],
      rulePack: [...this.form.controls.rulePack.value],
      testTaxonomy: [...this.form.controls.testTaxonomy.value],
      scenarioTemplate: [...this.form.controls.scenarioTemplate.value],
      projectMemory: [],
      priorityMapping: [],
      severityMapping: [...this.form.controls.severityMapping.value],
      synonymAlias: [...this.form.controls.synonymAlias.value],
    };
  }

  private getGenerationOptions(): GenerationOptions {
    return {
      includeSmoke: this.form.controls.includeSmoke.value,
      includeFunctional: this.form.controls.includeFunctional.value,
      includeNegative: this.form.controls.includeNegative.value,
      includeEdge: this.form.controls.includeEdge.value,
      includeUsability: this.form.controls.includeUsability.value,
      includeResponsiveness: this.form.controls.includeResponsiveness.value,
      includeCompatibility: this.form.controls.includeCompatibility.value,
      targetBrowsers: [...this.form.controls.targetBrowsers.value],
      screenSizes: [...this.form.controls.screenSizes.value],
    };
  }

  private extractPreviewCases(run: TestGenerationRunSummary | TestGenerationRunDetail | null): RunPreviewCase[] {
    if (!run) {
      return [];
    }

    const detail = 'parsedResponse' in run ? run.parsedResponse : null;
    const record = this.asRecord(detail);
    const cases = Array.isArray(record?.['testCases']) ? record['testCases'] : [];
    if (cases.length) {
      return cases
        .slice(0, 10)
        .map((item) => this.asRecord(item))
        .filter((item): item is Record<string, unknown> => !!item)
        .map((item) => ({
          title: String(item['title'] ?? 'Generated testcase'),
          feature: String(item['feature'] ?? 'Feature coverage'),
          scenario: String(item['scenario'] ?? 'Scenario expansion'),
        }));
    }

    return (run.progress?.previewTitles ?? []).map((title) => ({
      title,
      feature: this.suitePathLabel(),
      scenario: 'Live batch preview',
    }));
  }

  private asRecord(value: unknown): Record<string, unknown> | null {
    return value && typeof value === 'object' && !Array.isArray(value) ? (value as Record<string, unknown>) : null;
  }

  private guessMimeType(fileName: string) {
    if (/\.(html|htm)$/i.test(fileName)) {
      return 'text/html';
    }
    if (/\.xhtml$/i.test(fileName)) {
      return 'application/xhtml+xml';
    }
    if (/\.pdf$/i.test(fileName)) {
      return 'application/pdf';
    }
    if (/\.(doc|docx)$/i.test(fileName)) {
      return 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
    }
    if (/\.(xls|xlsx)$/i.test(fileName)) {
      return 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
    }
    if (/\.(png|jpg|jpeg|gif|webp)$/i.test(fileName)) {
      return 'image/*';
    }
    return 'application/octet-stream';
  }

  private readFileAsText(file: File) {
    return new Promise<string>((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(String(reader.result ?? ''));
      reader.onerror = () => reject(reader.error);
      reader.readAsText(file);
    });
  }

  private readFileAsDataUrl(file: File) {
    return new Promise<string>((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(String(reader.result ?? ''));
      reader.onerror = () => reject(reader.error);
      reader.readAsDataURL(file);
    });
  }

  private async buildFileBackedSource(kind: SourceKind, file: File): Promise<Partial<GenerationSourceInput>> {
    const isTextLike =
      file.type.startsWith('text/') ||
      /\.(txt|md|csv|json|yaml|yml|xml|html|htm|xhtml)$/i.test(file.name);

    const [dataUrl, contentText] = await Promise.all([
      this.readFileAsDataUrl(file),
      isTextLike ? this.readFileAsText(file) : Promise.resolve(''),
    ]);

    return {
      kind,
      label: file.name,
      filename: file.name,
      mimeType: file.type || this.guessMimeType(file.name),
      dataUrl,
      contentText,
    };
  }

  private ensureSourceVisible(index: number) {
    const card = document.querySelector<HTMLElement>(`[data-source-card-index="${index}"]`);
    card?.scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'nearest' });
  }
}
